{% include toc title="In This Lesson" icon="file-text" %}





<div class='notice--success' markdown="1">



## <i class="fa fa-graduation-cap" aria-hidden="true"></i> Learning Objectives

At the end of this activity, you will be able to:



* Understand the structure of and be able to create a vector object in R.



## <i class="fa fa-check-square-o fa-2" aria-hidden="true"></i> What you need



You need R and RStudio to complete this tutorial. Also we recommend have you

have an `earth-analytics` directory setup on your computer with a `/data`

directory with it.



* [How to Setup R / R Studio](/course-materials/earth-analytics-python/week-1/setup-r-rstudio/)

* [Setup your working directory](/course-materials/earth-analytics-python/week-1/setup-working-directory/)





</div>





## Vectors and data types



A vector is the most common data structure in `R`. A vector is defined as a

group of values, which most often are either numbers or characters. You can

assign this list of values to an object or variable, just like you

can for a single value. For example we can create a vector of animal weights:




In [1]:
import numpy as np

In [2]:
weight_g = np.array([50, 60, 65, 82])
weight_g

array([50, 60, 65, 82])

In [1]:
# ```{r weight-vector }

# weight_g <- c(50, 60, 65, 82)

# weight_g



# ```




A vector can also contain characters:




In [4]:
animals = np.array(['mouse', 'rat', 'dog'])
animals

array(['mouse', 'rat', 'dog'], 
      dtype='<U5')

In [1]:
# ```{r, purl=FALSE}

# animals <- c("mouse", "rat", "dog")

# animals

# ```




There are many functions that allow you to inspect the content of a

vector. `length()` tells you how many elements are in a particular vector:




In [5]:
len(weight_g)

4

In [6]:
len(animals)

3

In [1]:
# ```{r, purl=FALSE}

# length(weight_g)

# length(animals)

# ```




## Vector data types



An important feature of a vector, is that all of the elements are the same data

type. The function `class()` shows us the class (the data type) of an object:




In [7]:
type(weight_g)

numpy.ndarray

In [9]:
weight_g.dtype

dtype('int64')

In [10]:
animals.dtype

dtype('<U5')

In [1]:
# ```{r, purl=FALSE}

# class(weight_g)

# class(animals)

# ```




The function `str()` shows us the **structure** of the object and the elements it

contains. `str()` is a really useful function when working with large and complex

objects:




In [11]:
# Not sure what the equivalent of this is in numpy

'[50 60 65 82]'

In [1]:
# ```{r, purl=FALSE}

# str(weight_g)

# str(animals)

# ```




You can add elements to your vector by using the `c()` function:




In [13]:
# add the number 90 to the end of the vector
weight_g = np.hstack([weight_g, 90])

In [15]:
# add the number 30 to the beginning of the vector
weight_g = np.hstack([30, weight_g])

In [16]:
weight_g

array([30, 50, 60, 65, 82, 90])

In [1]:
# ```{r, purl=FALSE}



# # add the number 90 to the end of the vector

# weight_g <- c(weight_g, 90)



# # add the number 30 to the beginning of the vector

# weight_g <- c(30, weight_g)

# weight_g

# ```




In the examples above, we saw 2 of the 6 **atomic vector** types that `R` uses:



1. `"character"` and

2. `"numeric"`.



These are the basic data tpes that all `R` objects are built

from. The other 4 are:



* `"logical"` for `TRUE` and `FALSE` (the boolean data type)

* `"integer"` for integer numbers (e.g., `2L`, the `L` indicates to R that it's an integer)

* `"complex"` to represent complex numbers with real and imaginary parts (e.g.,

  `1+4i`) and that's all we're going to say about them

* `"raw"` that we won't discuss further



## Data type vs. data structure

Vectors are one of the many **data structures** that `R` uses. Other important

ones include: lists (`list`), matrices (`matrix`), data frames (`data.frame`) and

factors (`factor`). We will look at `data.frames` when we open our `boulder_precip`

data in the next lesson!



<div class="notice--warning" markdown="1">



## <i class="fa fa-pencil-square-o" aria-hidden="true"></i> Optional challenge activity



* **Question**: What happens when we create a vector that contains both numbers

and character values? Give it a try and write down the answer.

<!-- * _Answer_: R implicitly converts them to all be the same type -->



* **Question**: What will happen in each of these examples? (hint: use `class()`

  to check the data type of your objects):



```r

num_char <- c(1, 2, 3, 'a')

num_logical <- c(1, 2, 3, '2.45')

char_logical <- c('a', 'b', 'c', frog)

tricky <- c(1, 2, 3, '4')

```

* **Question**: Why do you think it happens?

<!-- * _Answer_: Vectors can be of only one data type. R tries to convert (=coerce)

  the content of this vector to find a "common denominator". -->



* **Question**: Can you draw a diagram that represents the hierarchy of the data

  types?

<!-- * _Answer_: `logical -> numeric -> character <-- logical` -->



</div>








In [18]:
num_char = np.array([1, 2, 3, 'a'])



num_logical = np.array([1, 2, 3, True])



char_logical = np.array(['a', 'b', 'c', True])



tricky = np.array([1, 2, 3, '4'])

In [1]:
# ```{r, echo=FALSE, eval=FALSE, purl=TRUE}

# ## We’ve seen that atomic vectors can be of type character, numeric, integer, and

# ## logical. But what happens if we try to mix these types in a single

# ## vector?



# ## What will happen in each of these examples? (hint: use `class()` to

# ## check the data type of your object)

# num_char <- c(1, 2, 3, 'a')



# num_logical <- c(1, 2, 3, TRUE)



# char_logical <- c('a', 'b', 'c', TRUE)



# tricky <- c(1, 2, 3, '4')



# ## Why do you think it happens?



# ## Can you draw a diagram that represents the hierarchy of the data

# ## types?

# ```






## Subsetting vectors



If we want to extract one or several values from a vector, we must provide one

or several indices in square brackets. For instance:




In [19]:
animals = np.array(["mouse", "rat", "dog", "cat"])
animals[2]


'dog'

In [20]:
animals[[2, 3]]

array(['dog', 'cat'], 
      dtype='<U5')

In [1]:
# ```{r, results='show', purl=FALSE}

# animals <- c("mouse", "rat", "dog", "cat")

# animals[2]

# animals[c(3, 2)]

# ```




<i fa fa-star></i>**Data Tip:** R indexes start at 1. Programming languages like

Fortran, MATLAB, and R start

counting at 1, because that's what human beings typically do. Languages in the C

family (including C++, Java, Perl, and Python) count from 0 because that's

simpler for computers to do.

{: .notice }

### ChrisH Note: this is a big oversimplification of 0 vs. 1 based indexing. :-)



## Subset Vectors



We can subset vectors too. For instance, if you wanted to select only the

values above 50:




In [21]:
weight_g > 50

array([False, False,  True,  True,  True,  True], dtype=bool)

In [23]:
# so we can use this to select only the values above 50
weight_g[weight_g > 50]

array([60, 65, 82, 90])

In [1]:
# ```{r, results='show', purl=FALSE}

# weight_g > 50    # will return logicals with TRUE for the indices that meet the condition

# ## so we can use this to select only the values above 50

# weight_g[weight_g > 50]

# ```




You can combine multiple tests using `&` (both conditions are true, AND) or `|`

(at least one of the conditions is true, OR):




In [26]:
weight_g[(weight_g < 30) | (weight_g > 50)]

array([60, 65, 82, 90])

In [27]:
weight_g[(weight_g >= 30) & (weight_g == 21)]

array([], dtype=int64)

In [1]:
# ```{r, results='show', purl=FALSE}

# weight_g[weight_g < 30 | weight_g > 50]

# weight_g[weight_g >= 30 & weight_g == 21]

# ```




When working with vectors of characters, if you are trying to combine many

conditions it can become tedious to type. The function `%in%` allows you to test

if a value is found in a vector:




In [34]:
animals = np.array(['mouse', 'rat', 'dog', 'cat'])
animals[(animals == 'cat') | (animals == 'rat')]

array(['rat', 'cat'], 
      dtype='<U5')

In [35]:
set(animals).intersection(set(['rat', 'cat', 'dog', 'duck']))

{'cat', 'dog', 'rat'}

In [36]:
animal_bool = [animal in animals for animal in ['rat', 'cat', 'dog', 'duck']]
animals[animal_bool]

array(['mouse', 'rat', 'dog'], 
      dtype='<U5')

In [37]:
# ```{r, results='show', purl=FALSE}

# animals <- c("mouse", "rat", "dog", "cat")

# animals[animals == "cat" | animals == "rat"] # returns both rat and cat

# animals %in% c("rat", "cat", "dog", "duck")

# animals[animals %in% c("rat", "cat", "dog", "duck")]

# ```




<div class="notice--warning" markdown="1">



## <i class="fa fa-pencil-square-o" aria-hidden="true"></i> Optional challenge



* Can you figure out why `"four" > "five"` returns `TRUE`?

</div>




* Can you figure out why `"four" > "five"` returns `True`?

In [1]:
# ```{r, echo=FALSE, purl=TRUE}

# # * Can you figure out why `"four" > "five"` returns `TRUE`?

# ```


## Answers

* When using ">" or "<" on strings, R compares their alphabetical order. Here "four" comes after "five", and therefore is "greater than" it.

In [1]:
```{r, purl=FALSE}

## Answers

## * When using ">" or "<" on strings, R compares their alphabetical order. Here

##   "four" comes after "five", and therefore is "greater than" it.

```
